# Generated by Django 5.2.3 on 2026-02-25 08:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('referral_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('daily_task_limit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Setting',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_type', models.CharField(choices=[('self', 'Self Earned'), ('referral', 'Referral Earned')], db_index=True, default='self', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='commission__user_id_4f841c_idx'), models.Index(fields=['triggered_by'], name='commission__trigger_010ca4_idx'), models.Index(fields=['commission_type'], name='commission__commiss_0e45a9_idx'), models.Index(fields=['created_at'], name='commission__created_9459c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product_name', 'commission_type', 'triggered_by'), name='unique_commission_per_trigger')],
            },
        ),
    ]
