"""
Django settings for AmazonProject project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
import urllib.parse
from pathlib import Path

from django.conf.locale import LANG_INFO
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

_raw_allowed = config('ALLOWED_HOSTS', default='')
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(',') if h.strip()]

_raw_csrf = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [
    origin if origin.startswith(('http://', 'https://')) else f'https://{origin}'
    for origin in [s.strip() for s in _raw_csrf.split(',') if s.strip()]
]

# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'modeltranslation',

    # Custom apps
    'accounts',
    'products',
    'balance',
    'wallet',
    'commission',
    'stoppoints',
    'language',
    'notification',
    'channels',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'accounts.middleware.AdminActivityMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AmazonProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AmazonProject.wsgi.application'
ASGI_APPLICATION = 'AmazonProject.asgi.application'

# ---------------------------------------------------------------------
# Chaannel layer to support multiple server -UPstash channel layer 
# ---------------------------------------------------------------------


REDIS_URL = os.environ.get("REDIS_URL")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}




# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASE_URL = config('DATABASE_URL', default='').strip()

if DATABASE_URL:
    url = urllib.parse.urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql' if url.scheme.startswith('postgres') else 'django.db.backends.sqlite3',
            'NAME': url.path[1:],
            'USER': url.username or '',
            'PASSWORD': url.password or '',
            'HOST': url.hostname or '',
            'PORT': url.port or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------
LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
    ('tr', _('Turkish')),
    ('ru', _('Russian')),
    ('az', _('Azerbaijani')),
    ('th', _('Thai')),
    ('be', _('Belarusian')),
    ('es', _('Spanish')),
    ('pt', _('Portuguese')),
    ('vi', _('Vietnamese')),
    ('sq', _('Albanian')),
    ('es-cl', _('Spanish (Chile)')),
    ('es-mx', _('Spanish (Mexico)')),
    ('en-ng', _('English (Nigeria)')),
    ('et', _('Estonian')),
]

LANG_INFO.update({
    'sq': {'bidi': False, 'code': 'sq', 'name': 'Albanian', 'name_local': 'Shqip'},
    'es-cl': {'bidi': False, 'code': 'es-cl', 'name': 'Spanish (Chile)', 'name_local': 'Chile'},
    'es-mx': {'bidi': False, 'code': 'es-mx', 'name': 'Spanish (Mexico)', 'name_local': 'Mexico'},
    'en-ng': {'bidi': False, 'code': 'en-ng', 'name': 'English (Nigeria)', 'name_local': 'Nigeria'},
    'et': {'bidi': False, 'code': 'et', 'name': 'Estonian', 'name_local': 'Eesti'},
})

LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True
USE_L10N = True
USE_TZ = True

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

# ---------------------------------------------------------------------
# Static and Media Files
# ---------------------------------------------------------------------
STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_URL = config('STATIC_URL', default='/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = config('MEDIA_URL', default='/media/')
if os.environ.get('RENDER') == 'true':
    MEDIA_ROOT = '/opt/render/project/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

INSTALLED_APPS += ["storages"]

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_ACCESS_KEY_ID = config("B2_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("B2_APP_KEY")
AWS_STORAGE_BUCKET_NAME = config("B2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = "https://s3.us-west-002.backblazeb2.com"
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 31536000

# ---------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_URL = '/accounts/userlogin/'
LOGIN_REDIRECT_URL = '/products/'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_LEVEL = 20

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

from django.utils.functional import SimpleLazyObject

def get_jazzmin_user_settings(request):
    user = getattr(request, "user", None)
    if not user or not user.is_authenticated:
        return {}

    settings = {"hide_apps": [], "hide_models": []}

    if getattr(user, "role", None) == "admin":
        settings["hide_apps"] = ["commission"]
    elif getattr(user, "role", None) == "customerservice":
        settings["hide_apps"] = ["commission", "products"]
        settings["hide_models"] = ["wallet.RechargeRequest"]
    elif getattr(user, "role", None) == "user":
        settings["hide_apps"] = ["*"]

    return settings

JAZZMIN_UI_TWEAKS = SimpleLazyObject(lambda: get_jazzmin_user_settings)
