# Generated by Django 5.2.3 on 2026-02-25 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unread_count', models.PositiveIntegerField(default=0)),
                ('superadmin_unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='Admin participant of the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('superadmin', models.ForeignKey(help_text='Super admin participant of the thread.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_chat_threads_as_superadmin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity',),
                'unique_together': {('admin', 'superadmin')},
            },
        ),
        migrations.CreateModel(
            name='StaffChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='staff_chat/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simplechat.staffchatthread')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserSupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_unread_count', models.PositiveIntegerField(default=0)),
                ('agent_unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Optional customer service agent overseeing the thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Regular user who owns this thread.', on_delete=django.db.models.deletion.CASCADE, related_name='support_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity',),
            },
        ),
        migrations.CreateModel(
            name='UserSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_chat/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simplechat.usersupportthread')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
