# Generated by Django 5.2.3 on 2026-02-25 08:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('required_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_bonus_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional one-time flat bonus amount awarded when this stop point product is completed.', max_digits=12, null=True)),
                ('bonus_disbursed', models.BooleanField(default=False, help_text='Tracks whether the stop-point bonus has already been credited to the wallet.')),
                ('bonus_disbursed_at', models.DateTimeField(blank=True, help_text='Timestamp when the stop-point bonus was credited to the wallet.', null=True)),
                ('recharged_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Cumulative recharge amount applied toward this stop point's requirement.", max_digits=12)),
                ('required_balance_remaining', models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding amount still needed to clear this stop point.', max_digits=12, null=True)),
                ('locked_task_price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of the next task price captured when the stop point triggers.', max_digits=12, null=True)),
                ('estimated_balance_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Projected balance shown to the user (includes bonus) when the stop point triggers.', max_digits=12, null=True)),
                ('lucky_order_enabled', models.BooleanField(default=False, help_text='If enabled, show lucky-order bonus messaging when this stop point triggers.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StopPointProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopped', models.BooleanField(default=False)),
                ('active_slice_pool_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active_slice_start_task', models.PositiveIntegerField(blank=True, null=True)),
                ('active_slice_end_task', models.PositiveIntegerField(blank=True, null=True)),
                ('active_slice_shares', models.JSONField(blank=True, help_text='Ordered base-share list for the current slice.', null=True)),
                ('active_slice_stop_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_slice_progress', to='stoppoints.stoppoint')),
                ('last_cleared', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stoppoints.stoppoint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
