# Generated by Django 5.2.3 on 2026-02-25 08:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum withdrawal amount in USD', max_digits=12)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum withdrawal amount per transaction in USD', max_digits=12)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Maximum total withdrawal amount per day in USD', max_digits=12)),
                ('min_leftover_balance', models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Minimum balance that must remain in wallet', max_digits=12)),
                ('trx20_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('erc20_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('bep20_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('polygon_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('solana_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('avalanche_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('fantom_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('arbitrum_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('optimism_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('cardano_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Configuration',
                'verbose_name_plural': 'Withdrawal Configuration',
            },
        ),
        migrations.CreateModel(
            name='UserWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet Address',
                'verbose_name_plural': 'User Wallet Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Requested withdrawal amount', max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='Transaction fee amount', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='Net amount after fees (amount - fee_amount)', max_digits=18)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('wallet_address', models.CharField(default='', help_text='Wallet address where funds will be sent', max_length=255)),
                ('balance_at_request', models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text="User's balance at time of withdrawal request", max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash (filled on approval)', max_length=255, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the withdrawal was approved/rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Withdrawal',
                'verbose_name_plural': 'User Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wallet_user_user_id_f34d9a_idx'), models.Index(fields=['created_at'], name='wallet_user_created_b38336_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_changed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': 'Wallet Histories',
                'ordering': ['-created_at'],
                'unique_together': {('address', 'network')},
            },
        ),
    ]
