# Generated by Django 5.2.3 on 2026-02-25 08:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='feature/')),
                ('link_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product', max_length=255)),
                ('name_en', models.CharField(default='Product', max_length=255, null=True)),
                ('name_ar', models.CharField(default='Product', max_length=255, null=True)),
                ('name_tr', models.CharField(default='Product', max_length=255, null=True)),
                ('name_ru', models.CharField(default='Product', max_length=255, null=True)),
                ('name_az', models.CharField(default='Product', max_length=255, null=True)),
                ('name_th', models.CharField(default='Product', max_length=255, null=True)),
                ('name_be', models.CharField(default='Product', max_length=255, null=True)),
                ('name_es', models.CharField(default='Product', max_length=255, null=True)),
                ('name_pt', models.CharField(default='Product', max_length=255, null=True)),
                ('name_vi', models.CharField(default='Product', max_length=255, null=True)),
                ('name_sq', models.CharField(default='Product', max_length=255, null=True)),
                ('name_es_cl', models.CharField(default='Product', max_length=255, null=True)),
                ('name_es_mx', models.CharField(default='Product', max_length=255, null=True)),
                ('name_en_ng', models.CharField(default='Product', max_length=255, null=True)),
                ('name_et', models.CharField(default='Product', max_length=255, null=True)),
                ('product_code', models.CharField(blank=True, max_length=11, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('description_ar', models.TextField(blank=True, default='', null=True)),
                ('description_tr', models.TextField(blank=True, default='', null=True)),
                ('description_ru', models.TextField(blank=True, default='', null=True)),
                ('description_az', models.TextField(blank=True, default='', null=True)),
                ('description_th', models.TextField(blank=True, default='', null=True)),
                ('description_be', models.TextField(blank=True, default='', null=True)),
                ('description_es', models.TextField(blank=True, default='', null=True)),
                ('description_pt', models.TextField(blank=True, default='', null=True)),
                ('description_vi', models.TextField(blank=True, default='', null=True)),
                ('description_sq', models.TextField(blank=True, default='', null=True)),
                ('description_es_cl', models.TextField(blank=True, default='', null=True)),
                ('description_es_mx', models.TextField(blank=True, default='', null=True)),
                ('description_en_ng', models.TextField(blank=True, default='', null=True)),
                ('description_et', models.TextField(blank=True, default='', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('file', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_number', models.PositiveSmallIntegerField(choices=[(1, 'Cycle 1'), (2, 'Cycle 2'), (3, 'Cycle 3')], db_index=True, default=1)),
                ('role_pool', models.CharField(choices=[('referee', 'Referee'), ('referrer', 'Referrer')], db_index=True, default='referee', max_length=20)),
                ('sequence_in_cycle', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCycleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_cycle', models.PositiveSmallIntegerField(choices=[(1, 'Cycle 1'), (2, 'Cycle 2'), (3, 'Cycle 3')], default=1)),
                ('referee_completed', models.BooleanField(default=False)),
                ('referrer_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('commissioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fake_display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('real_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fake_mode_task', models.BooleanField(default=False)),
                ('pricing_snapshot_daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_assigned', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'task_number'],
                'unique_together': {('user', 'product', 'round_number')},
            },
        ),
    ]
